QuanLyThietBi/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanLyThietBi.Controllers
{
    public class ProductController : Controller
    {
        //
        // GET: /Product/
        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        public ActionResult List()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }
	}
}

QuanLyThietBi/Controllers/ProductGroupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanLyThietBi.Controllers
{
    public class ProductGroupController : Controller
    {
        //
        // GET: /Product/
        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        public ActionResult List()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }
	}
}

QuanLyThietBi/Controllers/WareHouseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanLyThietBi.Controllers
{
    public class WareHouseController : Controller
    {
        // GET: WareHouse
        public ActionResult MoveProduct()
        {
            return View();
        }
    }
}

QuanLyThietBi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>SB Admin 2 - Bootstrap Admin Theme</title>
    <!-- Bootstrap Core CSS -->
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/plugins")
    @Styles.Render("~/fonts")
    @Scripts.Render("~/bundles/modernizr")
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <div id="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Quan Ly Thiet Bi</a>
            </div>
            @Html.Partial("_NavbarHeader")
            @Html.Partial("_Menu")
        </nav>
        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        @RenderBody()
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->
    </div>
    <!-- /#wrapper -->
    <!-- jQuery -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    @*@Scripts.Render("~/bundles/jquery")*@
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/plugins")
    @RenderSection("scripts", required: false)
</body>
</html>

QuanLyThietBi/Views/Shared/_Login.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>SB Admin 2 - Bootstrap Admin Theme</title>
    <!-- Bootstrap Core CSS -->
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/plugins")
    @Styles.Render("~/fonts")
    @Scripts.Render("~/bundles/modernizr")
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Please Sign In</h3>
                    </div>
                    <div class="panel-body">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    @*@Scripts.Render("~/bundles/jquery")*@
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/plugins")
    @RenderSection("scripts", required: false)
</body>
</html>

QuanLyThietBi/Views/Shared/_Menu.cshtml
<!-- /.navbar-top-links -->
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
            <li>
                <a href="#"><i class="fa fa-list fa-fw"></i> Product<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="@Url.Action("Index", "Product")"><i class="fa fa-list fa-fw"></i> List</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Create","Product")"><i class="fa fa-plus fa-fw"></i> Add New Product</a>
                    </li>
                </ul>
            </li>

            <li>
                <a href="#"><i class="fa fa-list fa-fw"></i> Product Group<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="@Url.Action("Index", "ProductGroup")"><i class="fa fa-list fa-fw"></i> List</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Create", "ProductGroup")"><i class="fa fa-plus fa-fw"></i> Add New Product Group</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="@Url.Action("MoveProduct", "WareHouse")"><i class="fa fa-university fa-fw"></i> Move Product</a>
                
            </li>
        </ul>
    </div>
    <!-- /.sidebar-collapse -->
</div>
<!-- /.navbar-static-side -->

QuanLyThietBi/Views/Shared/_NavbarHeader.cshtml
<!-- /.navbar-header -->
<ul class="nav navbar-top-links navbar-right">
    <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
        </a>
        <ul class="dropdown-menu dropdown-user">
            <li>
                <a href="#"><i class="fa fa-key fa-fw"></i> Change Password</a>
            </li>
            <li class="divider"></li>
            <li>
                <a href="@Url.Action("Login","Account")"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
            </li>
        </ul>
        <!-- /.dropdown-user -->
    </li>
    <!-- /.dropdown -->
</ul>